from typing import Union

RealNumber = Union[int, float]

# def add(x: int, y: int) -> int: ...
# def add(x: int|float, y: int|float) -> int|float: ...
# def add(x: RealNumber, y: RealNumber) -> RealNumber: ...
def add(x: float, y: float) -> float: ...
